micronaut:
  application:
    name: mnStockBroker
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
hello:
  service:
    greeting: "Hello from HelloService!"
  world:
    message: "Hello from application.yml"
    translation:
      de: "Hello Welt"
      en: "Hello World"
# JSON Settings
jackson:
  #  property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  generator:
    writeNumbersAsStrings: false
    writeBigDecimalAsPlain: false
  deserialization:
    failOnUnknownProperties: false
