POST localhost:8080/account/wallets/deposit
Content-Type: application/json

{
  "account_id": "f4245629-83df-4ed8-90d9-7401045b5921",
  "wallet_id": "f42456302-83df-4ed8-90d9-7401045b5123",
  "symbol": {
    "value": "EUR"
  },
  "amount": -50
}